language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

# before_install:
#     - gem install sass


before_script:
    - touch database/database.sqlite
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - pip install --user codecov
    - php artisan migrate --database=sqlite --force
    - php artisan key:generate

script:
    # - "tests/travis/scss.rb"
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)